import { CsTemplate } from "~/common";

export const templateRomancja: CsTemplate = {
  id: "pio3s:romancja",
  game: "Romancja",
  name: "Romancja",
  pageHeight: 794,
  pageWidth: 1123,
  fieldColor: "#fff",
  fieldStroke: "#000000",
  fieldFontSize: 33,
  pages: [
    {
      pos: 1,
      img: "cs/pio3s-romancja.webp",
      fields: [
        {
          id: "name",
          rect: [340, 208, 408, 58],
          name: "name",
          type: "text",
          fontSize: 33,
        },
        {
          id: "sila",
          name: "siła",
          rect: [967, 87, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Siła: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Siła: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Siła: utrudnienie",
            },
          ],
        },
        {
          id: "walka",
          name: "walka",
          rect: [967, 201, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Walka: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Walka: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Walka: utrudnienie",
            },
          ],
        },
        {
          id: "ruch",
          name: "ruch",
          rect: [967, 315, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Ruch: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Ruch: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Ruch: utrudnienie",
            },
          ],
        },
        {
          id: "urok",
          name: "urok",
          rect: [967, 431, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Urok: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Urok: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Urok: utrudnienie",
            },
          ],
        },
        {
          id: "rozum",
          name: "rozum",
          rect: [967, 544, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Rozum: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Rozum: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Rozum: utrudnienie",
            },
          ],
        },
        {
          id: "duch",
          name: "duch",
          rect: [967, 659, 48, 45],
          type: "attr",
          fontSize: 38,
          rolls: [
            {
              type: "target",
              dice: "2d10",
              srule: "pio3s:standard",
              comment: "Duch: standard",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:standard",
              comment: "Duch: ułatwienie",
            },
            {
              type: "target",
              dice: "3d10",
              srule: "pio3s:hard",
              comment: "Duch: utrudnienie",
            },
          ],
        },
        {
          id: "h1",
          rect: [74, 351, 25, 25],
          name: "h1",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h2",
          rect: [127, 351, 25, 25],
          name: "h2",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h3",
          rect: [180, 351, 25, 25],
          name: "h3",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h4",
          rect: [233, 351, 25, 25],
          name: "h4",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h5",
          rect: [286, 351, 25, 25],
          name: "h5",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h6",
          rect: [339, 351, 25, 25],
          name: "h6",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "h7",
          rect: [392, 351, 25, 25],
          name: "h7",
          type: "circle-check",
          stroke: "#ec3c3c",
        },
        {
          id: "p1",
          rect: [74, 456, 25, 25],
          name: "p1",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p2",
          rect: [127, 456, 25, 25],
          name: "p2",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p3",
          rect: [180, 456, 25, 25],
          name: "p3",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p4",
          rect: [233, 456, 25, 25],
          name: "p4",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p5",
          rect: [286, 456, 25, 25],
          name: "p5",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p6",
          rect: [339, 456, 25, 25],
          name: "p6",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "p7",
          rect: [392, 456, 25, 25],
          name: "p7",
          type: "circle-check",
          stroke: "#6795f0",
        },
        {
          id: "b1",
          rect: [125, 562, 25, 25],
          name: "b1",
          type: "circle-check",
          stroke: "#deba30",
        },
        {
          id: "b2",
          rect: [178, 562, 25, 25],
          name: "b2",
          type: "circle-check",
          stroke: "#deba30",
        },
        {
          id: "b3",
          rect: [232, 562, 25, 25],
          name: "b3",
          type: "circle-check",
          stroke: "#deba30",
        },
        {
          id: "b4",
          rect: [286, 562, 25, 25],
          name: "b4",
          type: "circle-check",
          stroke: "#deba30",
        },
        {
          id: "b5",
          rect: [340, 562, 25, 25],
          name: "b5",
          type: "circle-check",
          stroke: "#deba30",
        },
        {
          id: "ekwipunek",
          name: "ekwipunek",
          rect: [461, 355, 300, 367],
          type: "text",
          fontSize: 19,
          textAlign: "left",
        },
      ],
    },
    {
      pos: 2,
      img: "cs/pio3s-romancja-2.webp",
      fields: [
        {
          id: "notatki",
          name: "notatki",
          rect: [69, 245, 690, 486],
          type: "text",
          textAlign: "left",
          fontSize: 19,
        },
        {
          id: "osoby",
          name: "osoby",
          rect: [780, 140, 274, 590],
          type: "text",
          textAlign: "left",
          fontSize: 19,
        },
      ],
    },
  ],
};
