// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Charsheet is the predicate function for charsheet builders.
type Charsheet func(*sql.Selector)

// Roll is the predicate function for roll builders.
type Roll func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
