// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rpgroll/ent/charsheet"
	"rpgroll/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharsheetDelete is the builder for deleting a Charsheet entity.
type CharsheetDelete struct {
	config
	hooks    []Hook
	mutation *CharsheetMutation
}

// Where appends a list predicates to the CharsheetDelete builder.
func (cd *CharsheetDelete) Where(ps ...predicate.Charsheet) *CharsheetDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *CharsheetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *CharsheetDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *CharsheetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(charsheet.Table, sqlgraph.NewFieldSpec(charsheet.FieldID, field.TypeString))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// CharsheetDeleteOne is the builder for deleting a single Charsheet entity.
type CharsheetDeleteOne struct {
	cd *CharsheetDelete
}

// Where appends a list predicates to the CharsheetDelete builder.
func (cdo *CharsheetDeleteOne) Where(ps ...predicate.Charsheet) *CharsheetDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *CharsheetDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{charsheet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *CharsheetDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
