// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rpgroll/ent/predicate"
	"rpgroll/ent/rolldef"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RollDefDelete is the builder for deleting a RollDef entity.
type RollDefDelete struct {
	config
	hooks    []Hook
	mutation *RollDefMutation
}

// Where appends a list predicates to the RollDefDelete builder.
func (rdd *RollDefDelete) Where(ps ...predicate.RollDef) *RollDefDelete {
	rdd.mutation.Where(ps...)
	return rdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rdd *RollDefDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rdd.sqlExec, rdd.mutation, rdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rdd *RollDefDelete) ExecX(ctx context.Context) int {
	n, err := rdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rdd *RollDefDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rolldef.Table, sqlgraph.NewFieldSpec(rolldef.FieldID, field.TypeString))
	if ps := rdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rdd.mutation.done = true
	return affected, err
}

// RollDefDeleteOne is the builder for deleting a single RollDef entity.
type RollDefDeleteOne struct {
	rdd *RollDefDelete
}

// Where appends a list predicates to the RollDefDelete builder.
func (rddo *RollDefDeleteOne) Where(ps ...predicate.RollDef) *RollDefDeleteOne {
	rddo.rdd.mutation.Where(ps...)
	return rddo
}

// Exec executes the deletion query.
func (rddo *RollDefDeleteOne) Exec(ctx context.Context) error {
	n, err := rddo.rdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rolldef.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rddo *RollDefDeleteOne) ExecX(ctx context.Context) {
	if err := rddo.Exec(ctx); err != nil {
		panic(err)
	}
}
