// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rpgroll/ent/predicate"
	"rpgroll/ent/roll"
	"rpgroll/ent/room"
	"rpgroll/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RollQuery is the builder for querying Roll entities.
type RollQuery struct {
	config
	ctx        *QueryContext
	order      []roll.OrderOption
	inters     []Interceptor
	predicates []predicate.Roll
	withOwner  *UserQuery
	withRoom   *RoomQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RollQuery builder.
func (rq *RollQuery) Where(ps ...predicate.Roll) *RollQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RollQuery) Limit(limit int) *RollQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RollQuery) Offset(offset int) *RollQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RollQuery) Unique(unique bool) *RollQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RollQuery) Order(o ...roll.OrderOption) *RollQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryOwner chains the current query on the "owner" edge.
func (rq *RollQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roll.Table, roll.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roll.OwnerTable, roll.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoom chains the current query on the "room" edge.
func (rq *RollQuery) QueryRoom() *RoomQuery {
	query := (&RoomClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roll.Table, roll.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roll.RoomTable, roll.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Roll entity from the query.
// Returns a *NotFoundError when no Roll was found.
func (rq *RollQuery) First(ctx context.Context) (*Roll, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roll.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RollQuery) FirstX(ctx context.Context) *Roll {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Roll ID from the query.
// Returns a *NotFoundError when no Roll ID was found.
func (rq *RollQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roll.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RollQuery) FirstIDX(ctx context.Context) string {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Roll entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Roll entity is found.
// Returns a *NotFoundError when no Roll entities are found.
func (rq *RollQuery) Only(ctx context.Context) (*Roll, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roll.Label}
	default:
		return nil, &NotSingularError{roll.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RollQuery) OnlyX(ctx context.Context) *Roll {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Roll ID in the query.
// Returns a *NotSingularError when more than one Roll ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RollQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roll.Label}
	default:
		err = &NotSingularError{roll.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RollQuery) OnlyIDX(ctx context.Context) string {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rolls.
func (rq *RollQuery) All(ctx context.Context) ([]*Roll, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Roll, *RollQuery]()
	return withInterceptors[[]*Roll](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RollQuery) AllX(ctx context.Context) []*Roll {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Roll IDs.
func (rq *RollQuery) IDs(ctx context.Context) (ids []string, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(roll.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RollQuery) IDsX(ctx context.Context) []string {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RollQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RollQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RollQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RollQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RollQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RollQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RollQuery) Clone() *RollQuery {
	if rq == nil {
		return nil
	}
	return &RollQuery{
		config:     rq.config,
		ctx:        rq.ctx.Clone(),
		order:      append([]roll.OrderOption{}, rq.order...),
		inters:     append([]Interceptor{}, rq.inters...),
		predicates: append([]predicate.Roll{}, rq.predicates...),
		withOwner:  rq.withOwner.Clone(),
		withRoom:   rq.withRoom.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RollQuery) WithOwner(opts ...func(*UserQuery)) *RollQuery {
	query := (&UserClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withOwner = query
	return rq
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RollQuery) WithRoom(opts ...func(*RoomQuery)) *RollQuery {
	query := (&RoomClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRoom = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Tstamp string `json:"tstamp,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Roll.Query().
//		GroupBy(roll.FieldTstamp).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RollQuery) GroupBy(field string, fields ...string) *RollGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RollGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = roll.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Tstamp string `json:"tstamp,omitempty"`
//	}
//
//	client.Roll.Query().
//		Select(roll.FieldTstamp).
//		Scan(ctx, &v)
func (rq *RollQuery) Select(fields ...string) *RollSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RollSelect{RollQuery: rq}
	sbuild.label = roll.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RollSelect configured with the given aggregations.
func (rq *RollQuery) Aggregate(fns ...AggregateFunc) *RollSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RollQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !roll.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RollQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Roll, error) {
	var (
		nodes       = []*Roll{}
		withFKs     = rq.withFKs
		_spec       = rq.querySpec()
		loadedTypes = [2]bool{
			rq.withOwner != nil,
			rq.withRoom != nil,
		}
	)
	if rq.withOwner != nil || rq.withRoom != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, roll.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Roll).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Roll{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withOwner; query != nil {
		if err := rq.loadOwner(ctx, query, nodes, nil,
			func(n *Roll, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withRoom; query != nil {
		if err := rq.loadRoom(ctx, query, nodes, nil,
			func(n *Roll, e *Room) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RollQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Roll, init func(*Roll), assign func(*Roll, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Roll)
	for i := range nodes {
		if nodes[i].user_rolls == nil {
			continue
		}
		fk := *nodes[i].user_rolls
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_rolls" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *RollQuery) loadRoom(ctx context.Context, query *RoomQuery, nodes []*Roll, init func(*Roll), assign func(*Roll, *Room)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Roll)
	for i := range nodes {
		if nodes[i].room_rolls == nil {
			continue
		}
		fk := *nodes[i].room_rolls
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(room.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_rolls" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rq *RollQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RollQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roll.Table, roll.Columns, sqlgraph.NewFieldSpec(roll.FieldID, field.TypeString))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roll.FieldID)
		for i := range fields {
			if fields[i] != roll.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RollQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(roll.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = roll.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RollGroupBy is the group-by builder for Roll entities.
type RollGroupBy struct {
	selector
	build *RollQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RollGroupBy) Aggregate(fns ...AggregateFunc) *RollGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RollGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RollQuery, *RollGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RollGroupBy) sqlScan(ctx context.Context, root *RollQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RollSelect is the builder for selecting fields of Roll entities.
type RollSelect struct {
	*RollQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RollSelect) Aggregate(fns ...AggregateFunc) *RollSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RollSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RollQuery, *RollSelect](ctx, rs.RollQuery, rs, rs.inters, v)
}

func (rs *RollSelect) sqlScan(ctx context.Context, root *RollQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
